version: "3.7"

services:
  monitor:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
