version: "3.7"

services:
  hadoop-master:
    image: abdallahyossf/hadoop
    hostname: hadoop-master
    tty: true
    command: sh -c "service ssh start; ./start-hadoop.sh; bash"
    deploy:
      placement:
        constraints: [node.role == manager]

  hadoop-worker-1:
    image: abdallahyossf/hadoop
    hostname: hadoop-worker-1
    tty: true

  hadoop-worker-2:
    image: abdallahyossf/hadoop
    hostname: hadoop-worker-2
    tty: true
    

  hadoop-worker-3:
    image: abdallahyossf/hadoop
    hostname: hadoop-worker-3
    tty: true
    
