version: "3"
services:
  hadoop-master:
    image: abdallahyossf/hadoop
    container_name: hadoop-master
    tty: true
    command: sh -c "service ssh start; ./start-hadoop.sh; bash"
    depends_on:
      - hadoop-worker-1
      - hadoop-worker-2
      - hadoop-worker-3
    ports:
      -8088:8088
    deploy:
      placement:
        constraints: [node.role == manager]

  hadoop-worker-1:
    image: abdallahyossf/hadoop
    container_name: hadoop-worker-1
    tty: true

  hadoop-worker-2:
    image: abdallahyossf/hadoop
    container_name: hadoop-worker-2
    tty: true

  hadoop-worker-3:
    image: abdallahyossf/hadoop
    container_name: hadoop-worker-3
    tty: true
