version: "3.7"

services:
  hadoop-master:
    image: abdallahyossf/hadoop
    hostname: hadoop-master
    tty: true
    # this doesn't work well, it's better to wait for all nodes to come up and then start manually
    # command: sh -c "service ssh start; ./start-hadoop.sh; bash"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - main
    ports:
      - 8088:8088   # resource manager web app 
      - 10000:8042  # node manager web app 

  hadoop-worker-1:
    image: abdallahyossf/hadoop
    hostname: hadoop-worker-1
    tty: true
    networks:
      - main
    ports:
      - 10001:8042  # node manager web app 

  hadoop-worker-2:
    image: abdallahyossf/hadoop
    hostname: hadoop-worker-2
    tty: true
    networks:
      - main
    ports:
      - 10002:8042 # node manager web app 

  hadoop-worker-3:
    image: abdallahyossf/hadoop
    hostname: hadoop-worker-3
    tty: true
    networks:
      - main
    ports:
      - 10003:8042 # node manager web app 
    
networks:
  main:
    external: true